# ColorMe Teaming Plugin 1.4.6
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2013

world: 'world'

partyChatMode: false
opDisplayMode: false

firelyFireDisabler: true

ignoreGroups: ['', 'white', 'gold']

classes:
  Knight:
    items: 267,320:5
    armor: 306,307,308,309
  Archer:
    items: 261,262:50,297:4
    armor: 298,299,300,301
  Builder:
    items: 44:64,44@2:64,44@3:64,44@4:64,44@5:64
  Diver:
    items: 256^32-5^34-3,257^32-5^34-3,393:10
    armor: 306^5-3^6-1,0,0,309^2-4
  SuperWarrior:
    items: 267^16-5^17-5^18-5^19-2^20-2^34-3,282:10
    armor: 306^0-4^1-4^3-4^4-4,307^0-4^1-4^3-4^4-4,308^0-4^1-4^3-4^4-4,309^0-4^1-4^3-4^4-4
  Excalibur:
    items: 276^16-127@1561
    armor: 314,315,316,317

points:
  killPoint: 1
  deathPoint: -1
  tkPoint: -3

colorRemoveOnDeath: true
colorRemoveOnQuit: true

coloringDeathMessage: true

protectRespawnPointWithWorldGuard: false

protectRespawnPointRange: 3
