# ColorMe Teaming Plugin 1.4.10
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2013

# PVPを実施するworld名を設定してください。
world: 'world'

# サーバー起動時のチームチャットモードを設定します。
# trueになっている場合は、チャットの発言がチーム内のみになります。
teamChatMode: false

# teamChatMode が有効のときに、OPメンバーの画面にもチームチャットの内容を
# 表示するかどうかを設定します。
opDisplayMode: false

# 同じチームメンバー同士の攻撃（剣などの直接攻撃と、弓矢）を無効にします。
firelyFireDisabler: true

# teamChatMode、firelyFireDisabler、大将選出などの対象外とするグループを設定します。
# 管理者や、観客用のグループを設定してください。
ignoreGroups: ['', 'white', 'gold']

# クラスごとのインベントリーの内容を設定します。
# アイテムの設定形式は2種類あります。
# 通常のアイテム → (アイテムID)[@(ダメージ値)][:(個数)]
# エンチャント付きアイテム → (アイテムID)^(エンチャントID)-(エンチャントレベル)
classes:
  Knight:
    items: 267,320:5
    armor: 306,307,308,309
  Archer:
    items: 261,262:50,297:4
    armor: 298,299,300,301
  Builder:
    items: 44:64,44@2:64,44@3:64,44@4:64,44@5:64
  Diver:
    items: 256^32-5^34-3,257^32-5^34-3,393:10
    armor: 306^5-3^6-1,0,0,309^2-4
  SuperWarrior:
    items: 267^16-5^17-5^18-5^19-2^20-2^34-3,282:10
    armor: 306^0-4^1-4^3-4^4-4,307^0-4^1-4^3-4^4-4,308^0-4^1-4^3-4^4-4,309^0-4^1-4^3-4^4-4
  Excalibur:
    items: 276^16-300@1561
    armor: 314,315,316,317
  RedLeather:
    armor: 298$993333,299$993333,300$993333,301$993333
  BlueLeather:
    armor: 298$334CB2,299$334CB2,300$334CB2,301$334CB2
  YellowLeather:
    armor: 298$E5E533,299$E5E533,300$E5E533,301$E5E533
  GreenLeather:
    armor: 298$667F33,299$667F33,300$667F33,301$667F33

# ckillコマンド用の得点設定。
# killPoint - 他のチームのプレイヤーを倒したときの獲得点数。
# deathPoint - 誰かに倒されたときの獲得点数。
# tkPoint - 自分のチームのプレイヤーを倒したときの獲得点数。
#           cffがonで、チームメンバーへのダメージがないなら、設定の意味は無い。
points:
  killPoint: 1
  deathPoint: -1
  tkPoint: -3

# 死んでリスポンしたときに、グループから自動で抜けるかどうかを設定します。
colorRemoveOnDeath: true

# ログアウトしたときに、グループから自動で抜けるかどうかを設定します。
colorRemoveOnQuit: true

# デスメッセージ（死んだときに表示されるメッセージ）の名前を、
# ColorMeの色で表示するかどうかを設定します。
coloringDeathMessage: true

# 一般プレイヤーが、cjoin コマンドを使用して、グループを作ったり参加したりすることが
# できるようにするかを、設定します。
# allowPlayerJoinAny: true なら、/cjoin (group)  コマンドで、自由に参加するgroupを、
# 一般プレイヤーが作成したり参加したりすることができます。
# allowPlayerJoinRandom: true なら、/cjoin コマンドで、ランダムに人数の少ないグループに
# 参加することができるようになります。
allowPlayerJoinAny: false
allowPlayerJoinRandom: true

# いずれかのチームが指定のキル数に達したときに、通知を行うかどうかを設定します。
# 30を指定した場合は、30キル達成で通知します。0の場合は通知オフとなります。
# clコマンドで大将を選出している場合は、本設定は無視されることに注意してください。
killTrophy: 0

# いずれかのチームが指定のキル数に達したときに、通知を行うかどうかを設定します。
# 25を指定した場合は、25キル達成で「red チームは、あと 5キルで 30キルです！」と通知します。
# 0の場合は通知オフとなります。
# killTrophyが 0 の場合や、killTrophy より killReachTrophy が大きい場合は、この設定は無視されます。
# clコマンドで大将を選出している場合も、本設定は無視されます。
killReachTrophy: 0

# cspawnコマンドでチームのリスポーンポイントを設定したときに、
# リスポーンポイントの周囲を、他チームメンバーが進入できないように、
# WorldGuard を使って保護するかどうかを設定します。
# WorldGuard がロードされている必要があります。
protectRespawnPointWithWorldGuard: false

# protectRespawnPointWithWorldGuard が true のときに、
# リスポーンポイントから前後上下左右に何マスまでを保護領域にするかを設定します。
# 例）3を設定した場合、前後上下左右に3マス（7マス四方の立方体）で保護されます。
protectRespawnPointRange: 3

