# ColorMe Teaming Plugin 1.3.0
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2013

# サーバー起動時のチームチャットモードを設定します。
# trueになっている場合は、チャットの発言がチーム内のみになります。
teamChatMode: false

# teamChatMode が有効のときに、OPメンバーの画面にもチームチャットの内容を
# 表示するかどうかを設定します。
opDisplayMode: false

# 同じチームメンバー同士の攻撃（剣などの直接攻撃と、弓矢）を無効にします。
firelyFireDisabler: true

# teamChatMode、firelyFireDisabler、大将選出などの対象外とするグループを設定します。
# 管理者や、観客用のグループを設定してください。
ignoreGroups: ['', 'white', 'gold']

# クラスごとのインベントリーの内容を設定します。設定形式はClassSignと同じです。
classes:
    Knight:
        items: 267,320:5
        armor: 306,307,308,309
    Archer:
        items: 261,262:50,297:4
        armor: 298,299,300,301
    Builder:
        items: 44:64,44@2:64,44@3:64,44@4:64,44@5:64

# ckillコマンド用の得点設定。
# killPoint - 他のチームのプレイヤーを倒したときの獲得点数。
# deathPoint - 誰かに倒されたときの獲得点数。
# tkPoint - 自分のチームのプレイヤーを倒したときの獲得点数。
#           cffがonで、チームメンバーへのダメージがないなら、設定の意味は無い。
points:
    killPoint: 1
    deathPoint: -1
    tkPoint: -3

# 死んでリスポンしたときに、グループから自動で抜けるかどうかを設定します。
autoColorRemove: true
