# Color Teaming v2.2.6
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2013

# PVPを実施するworld名を設定してください。複数指定可能です。
worlds: ['world']

# サーバー起動時のチームチャットモードを設定します。
# trueになっている場合は、チャットの発言がチーム内のみになります。
teamChatMode: false

# teamChatMode が有効のときに、OPメンバーの画面にもチームチャットの内容を
# 表示するかどうかを設定します。
opDisplayMode: false

# チームチャットの内容を、コンソールに表示します。
# 同時に、server.log にも記録されます。
teamChatLogMode: true

# 同じチームメンバー同士の攻撃（剣などの直接攻撃と、弓矢やポーション）の
# 有効/無効を設定します。true → 攻撃が有効、false → 攻撃が無効
friendlyFire: false

# 透明化した同じチームメンバーが、見えるようにするかどうかを設定します。
# true → 透明化したメンバーが見える、false → 透明化したプレイヤーは誰からも見えない
seeFriendlyInvisible: true

# プレイヤー死亡時に、ゲームオーバーを表示せずにリスポーンするかどうかを設定します。
# true → ゲームオーバー画面を表示しないでそのままリスポーンする
# false → 通常通りゲームオーバーを表示する
skipGameover: false

# クラスを設定するときに、全回復するかどうかを設定します。
# 同時に、空腹度が回復、ポーション効果が全て消去されます。
healOnSetClass: true

# クラスごとのインベントリーの内容を設定します。
# アイテムの設定形式は2種類あります。
#   通常のアイテム → (アイテムID)[@(ダメージ値)][:(個数)]
#   エンチャント付きアイテム → (アイテムID)^(エンチャントID)-(エンチャントレベル)
# items : インベントリのアイテムを設定します。
# armor : (頭)、(胸)、(レギンス)、(足) の順に指定します。
#         0 を指定すると、その部分は装備しません。
# effect : ポーション効果を設定します。(エフェクトID)-(レベル)
#         レベルは0から始まりますので注意してください。
#         例）effect: 1-0,5-1,8-2 → 移動速度I、攻撃力II、跳躍力III
# experience : 経験値の量を設定します。数値のみを指定すれば、経験値配布の量を、
#              後ろにLをつければ、レベルでの配布量を指定できます。例）experience: 30L
classes:
  Knight:
    items: 267,320:5
    armor: 306,307,308,309
    effect: 1-0,5-1,8-2
    experience: 1000
  Archer:
    items: 261,262:50,297:4
    armor: 298,299,300,301
  Builder:
    items: 44:64,44@2:64,44@3:64,44@4:64,44@5:64
  Diver:
    items: 256^32-5^34-3,257^32-5^34-3,393:10
    armor: 306^5-3^6-1,0,0,309^2-4
  SuperWarrior:
    items: 267^16-5^17-5^18-5^19-2^20-2^34-3,282:10
    armor: 306^0-4^1-4^3-4^4-4,307^0-4^1-4^3-4^4-4,308^0-4^1-4^3-4^4-4,309^0-4^1-4^3-4^4-4
  Excalibur:
    items: 276^16-300@1561
    armor: 314,315,316,317
    effect: 1-5,5-5,8-5
    experience: 30L
  RedLeather:
    armor: 298$993333,299$993333,300$993333,301$993333
  BlueLeather:
    armor: 298$334CB2,299$334CB2,300$334CB2,301$334CB2
  YellowLeather:
    armor: 298$E5E533,299$E5E533,300$E5E533,301$E5E533
  GreenLeather:
    armor: 298$667F33,299$667F33,300$667F33,301$667F33

# cpointコマンド用の得点設定。
#   ctKillPoint - 他のチームのプレイヤーを倒したときの獲得点数。
#   ctDeathPoint - 誰かに倒されたときの獲得点数。
#   ctTKPoint - 自分のチームのプレイヤーを倒したときの獲得点数。
ctKillPoint: 1
ctDeathPoint: -1
ctTKPoint: -3

# 死んでリスポンしたときに、チームから自動で抜けるかどうかを設定します。
colorRemoveOnDeath: false

# ログアウトしたときに、チームから自動で抜けるかどうかを設定します。
colorRemoveOnQuit: false

# 死んでリスポンしたときに、ダメージを無効にする秒数を設定します。
# colorRemoveOnDeath が true だと、この設定は無視されますので注意してください。
noDamageSeconds: 5

# 一般プレイヤーが、/cjoin (group) コマンドを使用して、
# チームを作ったり参加したりすることができるようにするかを、設定します。
allowPlayerJoinAny: false

# 一般プレイヤーが、/cjoin コマンドで、ランダムに人数の少ないチームに
# 参加することができるようになります。
allowPlayerJoinRandom: true

# 一般プレイヤーが、/cleave コマンドを使用して、
# チームから離脱することができるようにするかを、設定します。
allowPlayerLeave: false

# サイドバーに表示するチームスコアの種類を指定します。
#   kill - キル数
#   death - デス数
#   point - ポイント(上記のpointsの項目を参照)
#   rest - 残り人数
#   none - 非表示
sideCriteria: rest

# listCriteria: TABキーリストに表示する個人スコアの種類を指定します。
#   kill - キル数
#   death - デス数
#   point - ポイント(上記のpointsの項目を参照)
#   health - 残り体力
#   none - 非表示
listCriteria: point

# 名前の下に表示する個人スコアの種類を指定します。
# 指定可能な項目は、listCriteriaと同じです。
belowCriteria: none

# いずれかのチームが指定のキル数に達したときに、通知を行うかどうかを設定します。
# 30を指定した場合は、30キル達成で通知します。0の場合は通知オフとなります。
# clコマンドで大将を選出している場合は、本設定は無視されることに注意してください。
killTrophy: 0

# いずれかのチームが指定のキル数に達したときに、通知を行うかどうかを設定します。
# 25を指定した場合は、25キル達成で
# 「red チームが、30 キルまでもう少しです(あと 5 キル)。」と通知します。
# 0の場合は通知オフとなります。
# killTrophyが 0 の場合や、killTrophy より killReachTrophy が大きい場合は、この設定は無視されます。
# clコマンドで大将を選出している場合も、本設定は無視されます。
killReachTrophy: 0

# チーム無所属の人がサーバーに参加したときに、
# ワールドのリスポーン地点へリスポーンするようになります。
# ワールドのリスポーン地点は、/cspawn world コマンドを使用してください。
worldSpawn: false

# 通常のチャットをJapanize化します。
showJapanizeGlobalChat: false

# チームチャットをJapanize化します。
showJapanizeTeamChat: true

# テレポート実行時の、ディレイ間隔を指定します。単位はtick（20tick=1秒）
teleportDelay: 2
