name: ColorTeaming
main: com.github.ucchyocean.ct.ColorTeaming
version: 1.5.8
authors: [ucchy,owatakun]
load: startup
description: 簡易PVPチーミングプラグイン
depend: []
softdepend: [WorldGuard]
commands:
  colorteaming:
    description: ColorTeamingの管理用コマンド
    aliases: ct
    usage: |
           /<command> reload - ColorMeTeaming の config.yml を再読み込みします。
           /<command> add (group) (player) - playerをgroupに追加します。
           /<command> remove (group) - groupを解散します。
           /<command> removeAll - 全てのグループを解散します。
           /<command> trophy (amount) - キル数達成時の通知を設定します。
           /<command> reachTrophy (amount) - キル数リーチ時の通知を設定します。
           /<command> side (kill|death|point|rest) - サイドバーのスコア表示を変更します。
           /<command> side clear - サイドバーのスコア表示を消去します。
           /<command> list (kill|death|point|health) - TABキーリストのスコア表示を変更します。
           /<command> list clear - TABキーリストのスコア表示を消去します。
           /<command> below (kill|death|point|health) - 名前下のスコア表示を変更します。
           /<command> below clear - 名前下のスコア表示を消去します。
    permission: colorteaming.team
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorrandom:
    description: 新しいチーム分けをランダムに設定するためのコマンド
    aliases: [crandom,randomcolor,rc]
    usage: |
           /<command> - 全てのプレイヤーを2チームにチーム分けします。
           /<command> (numberOfGroups) - 全てのプレイヤーを、numberOfGroupsの数のチームにチーム分けします。
           /<command> rest - 色が設定されていない人を、現在設定されているグループにランダム割り振りします。
    permission: colorteaming.random
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorcount:
    description: メンバーを一覧表示するコマンド
    aliases: cc
    usage: |
           /<command> - 各色グループのメンバーを一覧表示します。
           /<command> all - 全てのプレイヤー（ignoreGroups込み）のメンバーを一覧表示します。
           /<command> say [all] - 各色グループのメンバーの一覧を、サーバー全体メッセージで表示します。
    permission: colorteaming.count
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorcountsay:
    description: メンバーを一覧表示するコマンド
    aliases: ccsay
    usage: |
           /<command> - 各色グループのメンバーを、サーバー全体メッセージで表示します。
           /<command> all - 全てのプレイヤー（ignoreGroups込み）のメンバーを、サーバー全体メッセージで表示します。
    permission: colorteaming.count
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorfriendlyfire:
    description: メンバー間の攻撃の有効無効を切り替えるコマンド
    aliases: cff
    usage: |
           /<command> (on|off) - 各色グループのメンバー間の攻撃を、onで無効に、offで有効に設定します。
           /<command> invisible (on|off) - 各色グループの透明なメンバーを、onで見えるように、offで見えないようにします。
    permission: colorteaming.friendlyfire
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorchat:
    description: チームチャットの有効無効を切り替えるコマンド
    aliases: cchat
    usage: |
           /<command> (on|off) - 各色グループのメンバーのチャットを、onでチームチャットに、offで通常チャットに設定します。
           /<command> (opon|opoff) - 各チームのチームチャットを、OPが傍聴するかどうかを設定します。
           /<command> (logon|logoff) - 各チームのチームチャットを、server.logに記録します。
    permission: colorteaming.chat
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorleader:
    description: 各グループから大将を選出するコマンド
    aliases: cl
    usage: |
           /<command> (group) (player) - playerを、groupの大将に設定します。
           /<command> (group) random [(numberOfLeaders)] - groupの中からランダムに1人を、groupの大将に設定します。numberOfLeadersを指定した場合、指定した人数を大将として選出します。
           /<command> all [(numberOfLeaders)] - 全てのグループからランダムに1人を、各グループの大将に設定します。numberOfLeadersを指定した場合、指定した人数を各グループから大将として選出します。
           /<command> clear - 大将設定を削除します。
           /<command> view - 大将設定を表示します。
           /<command> say - 大将設定を、サーバー全体メッセージで表示します。
    permission: colorteaming.leader
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colortp:
    description: 各グループをテレポートするためのコマンド
    aliases: ctp
    usage: |
           /<command> (group) [(world)] (x) (y) (z) - groupのメンバー全員を、(world):(x),(y),(z) の場所にテレポートします。
           /<command> (group) here - groupのメンバー全員を、コマンドを実行した人の場所にテレポートします。
           /<command> (group) spawn - groupのメンバー全員を、グループのリスポーンポイントにテレポートします。
           /<command> (group) (point) - groupのメンバー全員を、指定されたポイントにテレポートします。
           /<command> set (point) [(world)] (x) (y) (z) - (world):(x),(y),(z) の場所に、新しいポイントを登録します。
           /<command> set (point) here - コマンドを実行した人の場所に、新しいポイントを登録します。
           /<command> remove (point) - 登録されたポイントを削除します。
           /<command> all spawn - 全てのプレイヤーを、グループのリスポーンポイントにテレポートします。
           /<command> all (point) - 全てのプレイヤーを、指定されたポイントにテレポートします。
           /<command> list - 登録されたポイントを一覧表示します。
    permission: colorteaming.tp
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorclass:
    description: インベントリを設定されたアイテムで初期化するためのコマンド
    aliases: cclass
    usage: |
           /<command> hand - 手に持っているアイテムの情報を表示します。
           /<command> (group) (class) - groupのメンバー全員のアイテムと装備を、config.yml の classes 設定に書かれているクラス設定のアイテムに変更します。
           /<command> (player) (class) - player のアイテムと装備を、config.yml の classes 設定に書かれているクラス設定のアイテムに変更します。
           /<command> all (class) - 全プレイヤーのアイテムと装備を、config.yml の classes 設定に書かれているクラス設定のアイテムに変更します。
    permission: colorteaming.class
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorkill:
    description: チームごとのキルデス数を表示するためのコマンド
    aliases: [ckill,ck]
    usage: |
           /<command> - 全てのグループごとのキルデス数カウントを参照します。
           /<command> say - 全てのグループごとのキルデス数カウントを、サーバー全体メッセージで表示します。
           /<command> clear - 全てのグループごとのキルデス数カウントを初期化して0にします。
    permission: colorteaming.kill
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorspawn:
    description: チームごとのリスポーンポイントを設定するためのコマンド
    aliases: [cspawn,cs]
    usage: |
           /<command> (group) - groupのメンバーのリスポーンポイントを、コマンドを実行した人の場所に設定します。
           /<command> (group) (MapName) - マップMapNameにおけるgroupのメンバーのリスポーンポイントを、コマンドを実行した人の場所に設定します。
           /<command> (group) (x) (y) (z) - groupのメンバー全員のリスポーンポイントを、(x),(y),(z) の場所に設定します。
           /<command> switch (MapName) - リスポーンポイントの設定を、MapNameに変更します。
           /<command> switch - リスポーンポイントの設定を、デフォルトに戻します。
           /<command> remove (group) - groupのリスポーンポイント設定を削除します。
           /<command> remove all - 全てのグループのリスポーン設定を削除します。
           /<command> world - ワールドのリスポーンポイントを設定します。
           /<command> list - リスポーン設定を一覧表示します。
    permission: colorteaming.spawn
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorremove:
    description: チームを離脱する条件を設定するためのコマンド
    aliases: cr
    usage: |
           /<command> death (on|off) - 死亡時に自動でチームから抜けるかどうかを設定します。
           /<command> quit (on|off) - ログアウト時に自動でチームから抜けるかどうかを設定します。
    permission: colorteaming.remove
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorsave:
    description: チーム分けのメンバー情報とキルデス数を保存するためのコマンド
    aliases: csave
    usage: |
           /<command> - チーム分けのメンバー情報とキルデス数を、"lastdata" という名前で保存します。
           /<command> (name) - チーム分けのメンバー情報とキルデス数を、nameという名前で保存します。
    permission: colorteaming.save
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorrestore:
    description: チーム分けのメンバー情報とキルデス数を、保存されたデータから復帰するためのコマンド
    aliases: crestore
    usage: |
           /<command> - チーム分けのメンバー情報とキルデス数を、"lastdata" から復帰します。
           /<command> (name) - チーム分けのメンバー情報とキルデス数を、nameという名前のデータから復帰します。
    permission: colorteaming.restore
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorexplode:
    description: チームを爆発させるコマンド（爆発オチ用）
    aliases: [ce,cexplode]
    usage: |
           /<command> (group) - groupのメンバー全員が爆発して死亡します。
           /<command> (player) - playerが爆発して死亡します。
    permission: colorteaming.explode
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorgive:
    description: チームメンバーのインベントリに、アイテムを追加するコマンド
    aliases: cgive
    usage: |
           /<command> (group) (item-id) - 指定したIDのアイテムを、groupのメンバー全員に配布します。
           /<command> (player) (item-id) - 指定したIDのアイテムを、playerに配布します。
           /<command> (group) hand - 手に持ったアイテムを、groupのメンバー全員に配布します。
           /<command> (player) hand - 手に持ったアイテムを、playerに配布します。
    permission: colorteaming.join
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorglobal:
    description: チームチャット有効時にグローバルへ発言するためのコマンド
    aliases: [cg,g]
    usage: /<command> (message) - チームチャットが設定されている状態で、通常のチャット発言を行います。
    permission: colorteaming.global
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  colorjoin:
    description: 一般プレイヤーが、任意のグループへ参加するためのコマンド
    aliases: cjoin
    usage: |
           /<command> (group) - groupに参加します。
           /<command> - 人数が少ないチームへ参加します。
           /<command> random - /<command> と同様です。
    permission: colorteaming.join
    permission-message: パーミッション "<permission>" が無いため、実行できません。
permissions:
  colorteaming.team:
    description: colorteaming(ct)コマンドの使用権限
    default: op
  colorteaming.random:
    description: colorrandom(crandom)コマンドの使用権限
    default: op
  colorteaming.count:
    description: colorcount(cc)コマンドの使用権限
    default: op
  colorteaming.friendlyfire:
    description: colorfriendlyfire(cff)コマンドの使用権限
    default: op
  colorteaming.chat:
    description: colorchat(cchat)コマンドの使用権限
    default: op
  colorteaming.leader:
    description: colorleader(cl)コマンドの使用権限
    default: op
  colorteaming.tp:
    description: colortp(ctp)コマンドの使用権限
    default: op
  colorteaming.class:
    description: colorclass(cclass)コマンドの使用権限
    default: op
  colorteaming.kill:
    description: colorkill(ckill)コマンドの使用権限
    default: op
  colorteaming.spawn:
    description: colorspawn(cspawn)コマンドの使用権限
    default: op
  colorteaming.remove:
    description: colorremove(cr)コマンドの使用権限
    default: op
  colorteaming.save:
    description: colorsave(csave)コマンドの使用権限
    default: op
  colorteaming.restore:
    description: colorrestore(crestore)コマンドの使用権限
    default: op
  colorteaming.explode:
    description: colorexplode(cexplode)コマンドの使用権限
    default: op
  colorteaming.*:
    children:
      colorteaming.team: true
      colorteaming.random: true
      colorteaming.count: true
      colorteaming.friendlyfire: true
      colorteaming.chat: true
      colorteaming.leader: true
      colorteaming.tp: true
      colorteaming.class: true
      colorteaming.kill: true
      colorteaming.spawn: true
      colorteaming.remove: true
      colorteaming.save: true
      colorteaming.restore: true
      colorteaming.explode: true
    description: ColorTeamingプラグインの管理系コマンド全ての使用権限
  colorteaming.global:
    description: colorglobal(g)コマンドの使用権限
    default: true
  colorteaming.join:
    description: colorjoin(cjoin)コマンドの使用権限
    default: true
