name: ColorMeTeaming
main: com.github.ucchyocean.cmt.ColorMeTeaming
version: 1.4.2
authors: [ucchy,owatakun]
load: startup
description: ColorMe Teaming Plugin
depend: [ColorMe]
softdepend: [TagAPI, WorldGuard]
commands:
  colorcount:
    description: ColorMe Count Command
    aliases: cc
    usage: /<command> - Display members of color groups.
    permission: colorteaming.count
    permission-message: You don't have permission "<permission>".
  colorcountsay:
    description: ColorMe Count Command
    aliases: ccsay
    usage: /<command> - Broadcast members of color groups.
    permission: colorteaming.count
    permission-message: You don't have permission "<permission>".
  colorfriendlyfire:
    description: ColorMe Friendly Fire Disabler Command
    aliases: cff
    usage: /<command> (on|off) - Set Friendly Fire on/off.
    permission: colorteaming.friendlyfire
    permission-message: You don't have permission "<permission>".
  colorchat:
    description: ColorMe Team Chat Command
    aliases: cchat
    usage: /<command> (on|off|opCopyOn|opCopyOff)
    permission: colorteaming.chat
    permission-message: You don't have permission "<permission>".
  colorglobal:
    description: Global Chat command for ColorMe Team Chat Command
    aliases: [cg,g]
    usage: /<command> (message)
    permission: colorteaming.global
    permission-message: You don't have permission "<permission>".
  colorleader:
    description: ColorMe Team Leaders Command
    aliases: cl
    usage: |
           /<command> (group) (user) - Set (user) for leader of (group).
           /<command> (group) random [(numberOfLeaders)]
           /<command> all [(numberOfLeaders)]
           /<command> clear - Clear all of leaders.
           /<command> view - Display leader information.
           /<command> say - Broadcast leader information.
    permission: colorteaming.leader
    permission-message: You don't have permission "<permission>".
  colortp:
    description: ColorMe Team Teleport Command
    aliases: ctp
    usage: |
           /<command> (group) [(world)] (x) (y) (z) - Teleport the members of (group) to (world):(x),(y),(z).
           /<command> (group) here - Teleport the members of (group) to here.
    permission: colorteaming.tp
    permission-message: You don't have permission "<permission>".
  colorclass:
    description: ColorMe Inventory Initializing Command
    aliases: cclass
    usage: /<command> (group|user) (class)
    permission: colorteaming.class
    permission-message: You don't have permission "<permission>".
  colorkill:
    description: ColorMe Team Kill-Death Count Command
    aliases: [ckill,ck]
    usage: /<command> [(say|clear)]
    permission: colorteaming.kill
    permission-message: You don't have permission "<permission>".
  colorspawn:
    description: ColorMe Team Spawn Set Command
    aliases: [cspawn,cs]
    usage: |
           /<command> (group) [(world)] (x) (y) (z) - Set the respawn point of (group) to (world):(x),(y),(z).
           /<command> (group) here - Set the respawn point of (group) to here.
    permission: colorteaming.spawn
    permission-message: You don't have permission "<permission>".
  colorrandom:
    description: ColorMe Random Team Setting Command
    aliases: [crandom,randomcolor,rc]
    usage: /<command> [(numberOfGroups)] - Make random teams.
    permission: colorteaming.random
    permission-message: You don't have permission "<permission>".
  colorremove:
    description: ColorMe Auto Color Remove Setting Command
    aliases: cr
    usage: /<command> (on|off) - Auto color remove on Player death.
    permission: colorteaming.remove
    permission-message: You don't have permission "<permission>".
  colorteaming:
    description: ColorMe Teaming Plugin Administration Command
    aliases: ct
    usage: |
           /<command> add (group) (user) - Add (user) to (group).
           /<command> remove (group) - Remove (group).
           /<command> removeAll - Remove all groups.
           /<command> reload - Reload config.yml file.
    permission: colorteaming.team
    permission-message: You don't have permission "<permission>".
permissions:
  colorteaming.count:
    description: ColorMe Count Command
    default: op
  colorteaming.friendlyfire:
    description: ColorMe Friendly Fire Disabler Command
    default: op
  colorteaming.chat:
    description: ColorMe Team Chat Command
    default: op
  colorteaming.leader:
    description: ColorMe Team Leaders Command
    default: op
  colorteaming.tp:
    description: ColorMe Team Teleport Command
    default: op
  colorteaming.class:
    description: ColorMe Inventory Initializing Command
    default: op
  colorteaming.kill:
    description: ColorMe Team Kill-Death Count Command
    default: op
  colorteaming.spawn:
    description: ColorMe Team Spawn Set Command
    default: op
  colorteaming.random:
    description: ColorMe Random Team Making Command
    default: op
  colorteaming.remove:
    description: ColorMe Color Remove on Death Command
    default: op
  colorteaming.team:
    description: ColorMe Teaming Plugin Administration Command
    default: op
  colorteaming.*:
    children:
      colorteaming.count: true
      colorteaming.friendlyfire: true
      colorteaming.chat: true
      colorteaming.leader: true
      colorteaming.tp: true
      colorteaming.class: true
      colorteaming.kill: true
      colorteaming.spawn: true
      colorteaming.random: true
      colorteaming.remove: true
      colorteaming.team: true
    description: Allows all commands for ColorMeTeaming
  colorteaming.global:
    description: Global Chat command for ColorMe Team Chat Command
    default: true
